server:
  port: 9999
  servlet:
    context-path: /auspostalinfo

spring:
  application:
    name: australiaPostalInfo
  datasource:
    url: jdbc:h2:mem:postcodedb
    driverClassName: org.h2.Driver
    username: user
    password: pa
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
